source=~/.config/hypr/hyprland/general.conf
exec-once=hyprpm reload
exec-once=hyprctl reload
### auto detection, failback to dwindle config if hy3 config caused error.
# exec-once=~/.config/hypr/scripts/failback_hy3_to_dwindle.sh
### DON'T TOUCH
source = ~/.config/hypr/hyprland/hy3/general.conf
# source = ~/.config/hypr/hyprland/dwindle/general.conf

source=~/.config/hypr/hyprland/monitor.conf
source=~/.config/hypr/hyprland/rules.conf
source=~/.config/hypr/hyprland/env.conf
# Load theme after general.conf to overwrite general.conf, but before execs.conf and keybinds.conf
source=~/.config/hypr/themesource.conf
source=~/.config/hypr/hyprland/keybinds.conf
source=~/.config/hypr/hyprland/execs.conf
