general {
    lock_cmd = pidof swaylock || swaylock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Long-idle mode: dim shortly before locking.
listener {
    timeout = 240                                # 4min
    on-timeout = brightnessctl -s s $(brightnessctl g | awk '{printf "%d", $1 * 0.4}')
    on-resume = brightnessctl -r
}

listener {
    timeout = 240                                # 4min
    on-timeout = brightnessctl -sd platform::kbd_backlight set 0
    on-resume = brightnessctl -rd platform::kbd_backlight
}

listener {
    timeout = 300                                # 5min
    on-timeout = loginctl lock-session
}

# Intentionally no DPMS-off or suspend listener in this mode.
