source=~/.config/hypr/hyprland/general.conf
exec-once=hyprpm reload
exec-once=hyprctl reload
exec-once=~/.config/hypr/scripts/check_hy3.sh

# Load theme after general.conf to overwrite general.conf, but before execs.conf and keybinds.conf
source=~/.config/hypr/themesource.conf

### DON'T TOUCH
source = ~/.config/hypr/hyprland/hy3/general.conf
# source = ~/.config/hypr/hyprland/dwindle/general.conf

source=~/.config/hypr/hyprland/env.conf
source=~/.config/hypr/hyprland/execs.conf
source=~/.config/hypr/hyprland/monitor.conf
source=~/.config/hypr/hyprland/rules.conf
source=~/.config/hypr/hyprland/keybinds.conf
