# Fixes
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --all
exec-once = xrdb ~/.Xresources
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
# exec-once = xwayland-satellite

# Cursor
# exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Bar, wallpaper
## restart swww-daemon everytime Hyprland reloads as swww-daemon adjust size wrongly after Hyprland reloads
# exec = pkill swww-daemon; swww-daemon
exec-once = awww-daemon
exec-once = sleep 0.1 && awww img ~/.config/hypr/wallpapers/$default_wallpaper
exec-once = waybar

# Input method
exec-once = fcitx5

# Core components (authentication, idle, notification daemon)
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = swaync

# Audio
# exec-once = easyeffects --gapplication-service
exec-once = musnify-mpd
exec-once = mpDris2

# Clipboard history
exec-once = wl-paste --watch ~/.config/hypr/scripts/cliprust.sh
exec-once = wl-clip-persist -c both -f "^(?!x-kde-passwordManagerHint\$).+"

# Start-ups
exec-once = [workspace 1 silent] librewolf
exec-once = [workspace 8 silent] clash-verge
exec-once = [workspace 10 silent] keepassxc
exec-once = sleep 1 && hyprctl dispatch movetoworkspacesilent 10, class:org.keepassxc.KeePassXC

# restart emacs to ensure envs are set correctly
exec-once = sleep 1 && systemctl --user restart emacs.service
