input {
    kb_layout = us
    kb_options = caps:escape
    follow_mouse = 1

    touchpad {
        disable_while_typing = false
        natural_scroll = true
        scroll_factor = 0.5
    }
}

# device {
#     name = e-signal-usb-gaming-mouse
#     sensitivity = -1
# }

misc {
    disable_hyprland_logo = true
}

debug {
    disable_logs = false
    suppress_errors = true
}

# gestures {
#     workspace_swipe = true
#     workspace_swipe_forever = true
# }

ecosystem {
    no_update_news = true
}
