# Variables
$mainMod = SUPER
$app_launcher = pkill wofi || wofi -c $wofi_config -s $wofi_theme
$clipboard = pkill wofi || cliprust -g wofi -t "Index	Preview" list | wofi -I -d -Dimage_size=256 -s $wofi_theme -k /dev/null | { read -r output  && cliprust decode <<< "$output" | { [ $? -eq 0 ] && wl-copy; }; }
source=$layout_keybinds

# Basics
bind = $mainMod, RETURN, exec, foot
bind = $mainMod SHIFT, RETURN, exec, emacsclient -c
bind = $mainMod, M, exec, swaylock -C $swaylock_config
bind = $mainMod, E, exec, thunar
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $app_launcher
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod, P, exec, $clipboard
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, T, exec, hyprpicker -a  # tools
bind = $mainMod, I, exec, ~/.config/hypr/scripts/toggle_hypridle_mode.sh  # toggle long-idle mode
bind = $mainMod, O, exec, /home/huangqixuan/.config/hypr/scripts/clipocr.sh | wl-copy
bind = ALT, Tab, focuscurrentorlast

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
# Notification Daemon
bind = $mainMod, N, exec, swaync-client --toggle-panel

bindl = $mainMod SHIFT, M, exec, hyprctl --instance 0 'dispatch exec swaylock'

# Pipewire
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = $mainMod, up, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = $mainMod, down, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
# bind = $mainMod, C, exec, echo "" > /home/huangqixuan/programming/projects/camexpcheat/r.txt
# bind = $mainMod, X, exec, echo "1" > /home/huangqixuan/programming/projects/camexpcheat/add1.txt
# Music player
bindl = $mainMod, SPACE, exec, mpc toggle
bindl = $mainMod SHIFT, SPACE, exec, playerctl play-pause
bindl = $mainMod SHIFT, PERIOD, exec, mpc next
bindl = $mainMod SHIFT, COMMA, exec, mpc prev
# Brightness
bind = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness.sh down
bind = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness.sh up
# Screenshots
$screenshot_path = ~/pictures/Screenshot_$(date +"%Y%m%d%H%M%S").png
bind = , Print, exec, pkill slurp || grim -g "$(slurp -w 0 -d)" - | wl-copy -t image/png
bind = ALT, Print, exec, pkill slurp || grim -g "$(slurp -w 0 -d)" $screenshot_path
bind = SHIFT, Print, exec, pkill slurp || grim - | wl-copy -t image/png
bind = ALT SHIFT, Print, exec, pkill slurp || grim $screenshot_path
