# MONITOR CONFIG
# monitor=eDP-1,2880x1800@60.00,auto,1.5,bitdepth,10 # 2880x1800 @ 1.5x in 14", 60 Hz [Built-in]
monitor=eDP-1,1920x1080@120.00,auto,1,bitdepth,10 # 1920x1080 in 14", 120 Hz [Built-in]
monitor=DP-1,1920x1080@100.00,auto,1,mirror,eDP-1,bitdepth,10
# monitor=eDP-1,preferred,auto,mirror,DP-1
# monitor=DP-1,1920x1080@60.00,auto,1

# misc {
#    vrr = 1
# }
# monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1

workspace = 2, monitor:eDP-1
