## Wechat
windowrulev2 = float,class:wechat
windowrulev2 = tile,class:wechat,title:微信
windowrulev2 = float,class:wechat,title:wechat
windowrulev2 = noborder,class:wechat,title:wechat
windowrulev2 = noblur, class:wechat
# windowrulev2 = fullscreen, class:^(wechat)$,title:^(微信)$
# windowrulev2 = forceinput,class:^(wechat)$,title:^(微信)$
# windowrulev2 = float, class:^(wechat)$, title:^(朋友圈)$

windowrulev2 = tag +alpha_1, class:librewolf
windowrulev2 = tag +alpha_1, class:wechat
windowrulev2 = opacity 1.0 override 1.0 override 1.0 override, tag:alpha_1
windowrulev2 = tag +term, class:footclient
windowrulev2 = tag +term, class:foot
windowrulev2 = pin,class:org.keepassxc.KeePassXC,floating:1


