## Wechat
windowrule {
  name = wechat-1
  float = on
  no_blur = on
  tag = +alpha_1
  match:class = wechat
}

windowrule {
  name = wechat-2
  tile = on
  match:class = wechat
  match:title = 微信（测试版）
}

windowrule {
  name = wechat-3
  float = on
  border_size = 0
  match:class = wechat
  match:title = wechat
}

windowrule {
  name = librewolf-1
  tag = +alpha_1
  match:class = librewolf
}

windowrule {
  name = no_opacity
  opacity = 1.0 override 1.0 override 1.0 override
  match:tag = alpha_1
}

windowrule {
  name = foot-1
  tag = +term
  match:class = footclient
}

windowrule {
  name = foot-2
  tag = +term
  match:class = foot
}

windowrule {
  name = keepassxc-1
  pin = on
  match:class = org.keepassxc.KeePassXC
  match:float = 1
}



## XwaylandVideoBridge
windowrule {
  name = hide_xwaylandvideobridge
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
  no_focus = on
  match:class = ^(xwaylandvideobridge)$
}



# workspace = 1,monitor:DP-1
# workspace = 2,monitor:DP-1
# workspace = 3,monitor:DP-1
# workspace = 4,monitor:DP-1
# workspace = 5,monitor:DP-1
# workspace = 6,monitor:DP-1
# workspace = 7,monitor:eDP-1
# workspace = 8,monitor:DP-1
# workspace = 9,monitor:DP-1
# workspace = 10,monitor:DP-1


