vim.keymap.del("n", "<leader>gG")
vim.keymap.del("n", "<leader>gg")
vim.keymap.del("n", "<leader>gb")
vim.keymap.del("n", "<leader>gf")
vim.keymap.del("n", "<leader>gB")
vim.keymap.del("n", "<leader>gl")
vim.keymap.del("n", "<leader>gL")
